kafka:
  bootstrapServers: "PLAINTEXT://kafka-headless.kafka:9092" 

cp-schema-registry:
  url: kafka-schema-registry.kafka"

serviceType: LoadBalancer

prometheus:
  jmx:
    enabled: false

livenessProbe:
  httpGet:
     path: /connectors
     port: 8083
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 10
